Added Brazilian Portuguese on extension
XFox111/TabsAsideExtension pull request #54
Opened 2020-10-15 11:48 UTC by amandafilizola

Implements following issues: 

## Changelog
- added a pt_BR folder on _locales
## PR Checklist
- [x] Change extension version in the manifest

2020-10-15 12:01 UTC, XFox111 requested changes
Thank you for the contribution!
I've reviewed the PR. There're some minor changes required to be made but overall quality is perfect (at least as far as I trust Google Translate). Great job!

2020-10-15 12:01 UTC, XFox111 commented on manifest.json
> +	"version": "2.0.1",
There's no need to update manifest version since v2.0 has not been shipepd yet. Revert this change please

2020-10-15 12:01 UTC, XFox111 commented on _locales/pt_BR/messages.json
> +	"contributors":
In version 2.0 this menu item will be replaced with "Changelog" menu item which will lead to GitHub Releases. 

So this:
```json
"contributors":
{
    "message": "Project contributors",
    "description": "Link title"
},
```
Must be replaced with this (with appropriate translation, of course):
```json
"changelog":
{
    "message": "Changelog",
    "description": "Link title"
},
```

2020-10-15 12:11 UTC, amandafilizola commented on manifest.json
> +	"version": "2.0.1",
Updated.

2020-10-15 12:12 UTC, amandafilizola commented on _locales/pt_BR/messages.json
> +	"contributors":
Updated.

2020-10-16 06:00 UTC, XFox111 approved these changes

2020-10-16 06:02 UTC, merged

2020-10-16 06:05 UTC, XFox111 commented
Thank you for being interested in my project! It's really important to me.
Your changes have been merged into 2.0 version branch and will be published as soon as the version will be ready to deliver