Change default 'set tabs aside' shortcut
XFox111/TabsAsideExtension pull request #90
Opened 2022-06-29 19:25 UTC by aamott

This shortcut can cause problems for those who are accustomed to using it to go back in history. In Chrome and Edge, it seems to be overridden. Shift+Alt+Left is an unused key combo. 

Implements following issue:
 [Default shortcut overrides browser hotkeys #89](https://github.com/XFox111/TabsAsideExtension/issues/89)

## Changelog
- Changed "Set Tabs Aside" shortcut to `Shift+Alt+Left`

2022-07-22 12:08 UTC, XFox111 requested changes
Hi, thanks for your contribution!
There's one more change to be made. Please change extension version in the manifest file from `2.0.5` to `2.0.6`. It is required for automation pipelines to deploy a newer version to stores

2022-08-23 19:04 UTC, aamott commented
Got that updated. Thanks!

2022-08-23 19:05 UTC, aamott commented
Accidentally clicked "close and comment"...

2022-08-25 14:05 UTC, XFox111 approved these changes
Yeah, seems good. Thanks)

2022-08-25 14:06 UTC, merged